language: python
services: mongodb
python:
  - "2.7"
  - "3.3"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - pip install coverage
  - pip install python-coveralls
before_script:
  - python setup.py develop
script:
  - nosetests --nocapture --with-coverage
  - source fireworks/tests/cmd_line_test.sh
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - ajain@lbl.gov
      - dkgunter@lbl.gov
      - ongsp@ucsd.edu
      - xqu@lbl.gov
      - g.petretto@gmail.com
    on_success: change
    on_failure: always
